### ISSUE TITLE
some error in yelp_prepare.py

### ISSUE THREAD

**Issue by jianzhengming** [ematvey/hierarchical-attention-networks#10]
When i run the yelp_prepare.py, it told me that `ValueError: sentence boundary detection requires the dependency parse, which requires data to be installed. For more info, see the documentation:`(http://spacy.io/docs/usage)
Could you please give me some advice!
Thanks a lot!

**Comment by ematvey** [comment]
Try `python -m spacy download en`

**Comment by jianzhengming** [comment]
Thanks for your attention.
But, it encounters a new problem. ImportError: No module named 'en_core_web_sm'.
Could you help me again?
Thank you!

**Comment by ematvey** [comment]
Fault is mine for not including proper install instructions with virtualenv. Still, you probably should solve these kinds of issues by googling, stackoverflow has all the answers.

**Comment by jianzhengming** [comment]
Thanks all the same.
